/*
 * SPDX-FileCopyrightText: syuilo and misskey-project
 * SPDX-License-Identifier: AGPL-3.0-only
 */

export const PUBLIC_SEARCH_QUERY_MAX_LENGTH = 256;
export const PUBLIC_TAG_MAX_LENGTH = 128;
export const PUBLIC_HOST_MAX_LENGTH = 253;
export const PUBLIC_EMAIL_MAX_LENGTH = 320;
export const PUBLIC_URL_MAX_LENGTH = 2048;
export const PUBLIC_TOKEN_MAX_LENGTH = 128;
export const PUBLIC_PASSWORD_MAX_LENGTH = 1024;
export const PUBLIC_USER_IDS_MAX_ITEMS = 500;
export const MISSKEY_ID_MAX_LENGTH = 64;
export const PUBLIC_TAG_QUERY_MAX_ITEMS = 8;
export const PUBLIC_CHART_OFFSET_MAX_TIMESTAMP = 8640000000000000;
export const PUBLIC_APP_NAME_MAX_LENGTH = 128;
export const PUBLIC_APP_DESCRIPTION_MAX_LENGTH = 512;
export const PUBLIC_APP_ICON_URL_MAX_LENGTH = 512;
export const API_PERMISSION_MAX_ITEMS = 128;
export const API_PERMISSION_MAX_LENGTH = 64;
export const PUBLIC_EMOJI_NAME_MAX_LENGTH = 128;
export const PUBLIC_GAME_MODE_MAX_LENGTH = 128;
export const PUBLIC_ENDPOINT_NAME_MAX_LENGTH = 256;
export const PUBLIC_TRANSLATION_TARGET_LANG_MAX_LENGTH = 32;
export const PUBLIC_REACTION_TYPE_MAX_LENGTH = 512;
export const PUBLIC_CRC32_MAX_LENGTH = 16;
