/*
 * SPDX-FileCopyrightText: syuilo and misskey-project
 * SPDX-License-Identifier: AGPL-3.0-only
 */

/// <reference types="vite/client" />

import { assert, describe, test } from 'vitest';
import settingsIndexSource from '@/pages/settings/index.vue?raw';
import developerCenterSource from '@/pages/settings/connect.vue?raw';
import mkApiScopePickerSource from '@/components/MkApiScopePicker.vue?raw';
import adminIndexSource from '@/pages/admin/index.vue?raw';
import adminApiSource from '@/pages/admin/api.vue?raw';
import routerSource from '@/router.definition.ts?raw';
import backendConstSource from '../../backend/src/const.ts?raw';
import endpointListSource from '../../backend/src/server/api/endpoint-list.ts?raw';
import apiCallServiceSource from '../../backend/src/server/api/ApiCallService.ts?raw';
import apiAccessUtilsSource from '../../backend/src/server/api/api-access-utils.ts?raw';
import authenticateServiceSource from '../../backend/src/server/api/AuthenticateService.ts?raw';
import legacyAppCreateSource from '../../backend/src/server/api/endpoints/app/create.ts?raw';
import developerAppCreateSource from '../../backend/src/server/api/endpoints/api/apps/create.ts?raw';
import developerAppUpdateSource from '../../backend/src/server/api/endpoints/api/apps/update.ts?raw';
import adminAccessRequestsListSource from '../../backend/src/server/api/endpoints/admin/api/access-requests/list.ts?raw';
import adminAppsListSource from '../../backend/src/server/api/endpoints/admin/api/apps/list.ts?raw';
import adminAppUpdateSource from '../../backend/src/server/api/endpoints/admin/api/apps/update.ts?raw';
import adminTokensListSource from '../../backend/src/server/api/endpoints/admin/api/tokens/list.ts?raw';
import adminApiSummarySource from '../../backend/src/server/api/endpoints/admin/api/usage/summary.ts?raw';
import adminApiSettingsShowSource from '../../backend/src/server/api/endpoints/admin/api/settings/show.ts?raw';
import adminApiSettingsUpdateSource from '../../backend/src/server/api/endpoints/admin/api/settings/update.ts?raw';
import authSessionGenerateSource from '../../backend/src/server/api/endpoints/auth/session/generate.ts?raw';
import authAcceptSource from '../../backend/src/server/api/endpoints/auth/accept.ts?raw';
import authUserkeySource from '../../backend/src/server/api/endpoints/auth/session/userkey.ts?raw';
import developerTokenCreateSource from '../../backend/src/server/api/endpoints/api/tokens/create.ts?raw';
import oauthServiceSource from '../../backend/src/server/oauth/OAuth2ProviderService.ts?raw';
import mastodonAppsSource from '../../backend/src/server/api/mastodon/endpoints/apps.ts?raw';
import wellKnownSource from '../../backend/src/server/WellKnownServerService.ts?raw';
import apiDeveloperCenterMigrationSource from '../../backend/migration/1780700000000-api-developer-center.js?raw';
import dropDefaultCallbackMigrationSource from '../../backend/migration/1780700000002-drop-api-default-oauth-callback-url.js?raw';
import markPersonalTokensMigrationSource from '../../backend/migration/1780700000003-mark-personal-api-tokens-developer.js?raw';

describe('API developer center', () => {
	test('exposes clear user and admin entry points', () => {
		assert.include(settingsIndexSource, '开发者中心');
		assert.include(settingsIndexSource, "to: '/settings/connect'");
		assert.include(settingsIndexSource, "icon: 'ti ti-api'");

		assert.include(adminIndexSource, 'API 管理');
		assert.include(adminIndexSource, "to: '/admin/api'");
		assert.include(routerSource, "path: '/api'");
		assert.include(routerSource, "import('@/pages/admin/api.vue')");
	});

	test('documents API modes, templates, token actions, and OAuth examples', () => {
		assert.include(developerCenterSource, 'API 使用状态');
		assert.include(developerCenterSource, '快捷登录');
		assert.include(developerCenterSource, '发布资源/发帖');
		assert.include(developerCenterSource, '发帖 + 上传附件');
		assert.include(developerCenterSource, '机器人/自动同步');
		assert.include(developerCenterSource, '每个应用必须填写自己的 OAuth/OIDC 回调地址');
		assert.include(developerCenterSource, 'OAuth/OIDC 回调地址');
		assert.include(developerCenterSource, '这个地址由应用所有者填写，管理员不会代填');
		assert.include(developerCenterSource, ':placeholder="defaultAppCallbackPlaceholder"');
		assert.include(developerCenterSource, 'const defaultAppCallbackPlaceholder = computed(() => `${window.location.origin}/oauth/callback`)');
		assert.notInclude(developerCenterSource, 'https://example.com/oauth/callback');
		assert.include(developerCenterSource, 'newAppCallbackUrl');
		assert.include(developerCenterSource, 'newAppCallbackUrl.value.trim()');
		assert.include(developerCenterSource, 'callbackUrls: [newAppCallbackUrl.value.trim()]');
		assert.notInclude(developerCenterSource, 'defaultOAuthCallbackUrl');
		assert.notInclude(developerCenterSource, 'effectiveAppCallbackUrl');
		assert.notInclude(developerCenterSource, 'callbackPreview');
		assert.notInclude(developerCenterSource, '管理员默认值只作为初始建议');
		assert.notInclude(developerCenterSource, 'newAppWebsiteUrl');
		assert.notInclude(developerCenterSource, 'customAppRedirectUri');
		assert.notInclude(developerCenterSource, 'buildDefaultRedirectUri');
		assert.notInclude(developerCenterSource, 'websiteUrl: newAppWebsiteUrl');
		assert.include(developerCenterSource, "method: 'POST', path: '/api/notes/create'");
		assert.include(developerCenterSource, "method: 'POST', path: '/api/notes/delete'");
		assert.include(developerCenterSource, "method: 'GET', path: '/oauth/authorize'");
		assert.include(developerCenterSource, '/oauth/userinfo');
		assert.include(developerCenterSource, "permissions: ['read:profile']");
		assert.include(developerCenterSource, 'scope=read:profile');
		assert.include(developerCenterSource, "misskeyApi<ApiAccessStatus>('api/access/status'");
		assert.include(developerCenterSource, "misskeyApi<ApiApp>('api/apps/create'");
		assert.include(developerCenterSource, "misskeyApi<{ id: string; token: string }>('api/tokens/create'");
		assert.include(developerCenterSource, "misskeyApi('api/tokens/revoke'");
	});

	test('admin page manages settings, approvals, apps, tokens, and usage', () => {
		assert.include(adminApiSource, 'API 开放设置');
		assert.include(adminApiSource, '<option value="approval">申请使用</option>');
		assert.include(adminApiSource, '<option value="open">开放使用</option>');
		assert.include(adminApiSource, '<option value="closed">关闭使用</option>');
		assert.include(adminApiSource, '允许普通开发者使用的权限范围');
		assert.include(adminApiSource, 'OAuth/OIDC 回调地址由每个应用的所有者在开发者中心填写');
		assert.notInclude(adminApiSource, '默认 OAuth/OIDC 回调地址');
		assert.notInclude(adminApiSource, 'settings.defaultOAuthCallbackUrl');
		assert.notInclude(adminApiSource, '作为普通开发者创建应用时的默认建议地址');
		assert.include(adminApiSource, '权限范围');
		assert.include(adminApiSource, '<MkApiScopePicker');
		assert.include(adminApiSource, '恢复推荐默认');
		assert.include(mkApiScopePickerSource, '全选');
		assert.include(mkApiScopePickerSource, '清空');
		assert.include(mkApiScopePickerSource, 'function selectAll');
		assert.notInclude(adminApiSource, 'publicPermissionsText');
		assert.notInclude(adminApiSource, '<MkTextarea v-model="publicPermissionsText"');
		assert.include(adminApiSource, "scope: 'read:profile'");
		assert.include(adminApiSource, '快捷登录资料');
		assert.include(adminApiSource, '读取账号 API 资料');
		assert.include(adminApiSource, 'recommendedPublicPermissions');
		assert.include(adminApiSource, "scope: 'read:account'");
		assert.include(adminApiSource, "scope: 'write:notes'");
		assert.include(adminApiSource, "scope: 'read:drive'");
		assert.include(adminApiSource, "scope: 'write:drive'");
		assert.include(adminApiSource, "scope: 'read:channels'");
		assert.include(adminApiSource, "scope: 'write:channels'");
		assert.include(adminApiSource, "scope: 'read:following'");
		assert.include(adminApiSource, "scope: 'write:following'");
		assert.include(adminApiSource, "scope: 'read:blocks'");
		assert.include(adminApiSource, "scope: 'write:blocks'");
		assert.include(adminApiSource, "scope: 'read:mutes'");
		assert.include(adminApiSource, "scope: 'write:mutes'");
		assert.include(adminApiSource, "scope: 'read:notifications'");
		assert.include(adminApiSource, "scope: 'write:notifications'");
		assert.include(adminApiSource, "scope: 'read:chat'");
		assert.include(adminApiSource, "scope: 'write:chat'");
		assert.include(adminApiSource, "misskeyApi<ApiSettings>('admin/api/settings/show'");
		assert.include(adminApiSource, "misskeyApi<ApiSettings>('admin/api/settings/update'");
		assert.include(adminApiSource, 'publicPermissions: normalizePublicPermissionSelection(settings.value.publicPermissions)');
		assert.include(adminApiSource, "misskeyApi<ApiSummary>('admin/api/usage/summary'");
		assert.notInclude(adminApiSource, '<MkPagination');
		assert.notInclude(adminApiSource, 'offsetMode: true');
		assert.include(adminApiSource, 'createPagedListState');
		assert.include(adminApiSource, 'loadPagedList');
		assert.include(adminApiSource, 'normalizePagedResult');
		assert.include(adminApiSource, 'Array.isArray(result.items) ? result.items : []');
		assert.include(adminApiSource, "misskeyApi<ApiPagedResult<T>, string>(endpoint");
		assert.include(adminApiSource, 'withTotal: true');
		assert.include(adminApiSource, "const pageSizeValues = ['20', '50', '100']");
		assert.include(adminApiSource, '<template #label>每页数量</template>');
		assert.include(adminApiSource, '<template #label>跳页</template>');
		assert.include(adminApiSource, '首页');
		assert.include(adminApiSource, '上一页');
		assert.include(adminApiSource, '下一页');
		assert.include(adminApiSource, '末页');
		assert.include(adminApiSource, '共 {{ accessRequestsState.total }} 条');
		assert.include(adminApiSource, '共 {{ appsState.total }} 条');
		assert.include(adminApiSource, '共 {{ tokensState.total }} 条');
		assert.include(adminApiSource, 'pageRangeStart');
		assert.include(adminApiSource, 'pageRangeEnd');
		assert.include(adminApiSource, 'applyAccessRequestFilters');
		assert.include(adminApiSource, 'applyAppFilters');
		assert.include(adminApiSource, '<template #label>个人 API Token</template>');
		assert.include(adminApiSource, 'tokensState.queryInput');
		assert.include(adminApiSource, 'tokensState.userIdInput');
		assert.include(adminApiSource, 'applyTokenFilters');
		assert.include(adminApiSource, 'clearTokenFilters');
		assert.include(adminApiSource, 'Token ID：');
		assert.include(adminApiSource, '说明：');
		assert.include(adminApiSource, '最近使用：');
		assert.include(adminAccessRequestsListSource, 'enum: [...apiAccessGrantStatuses, null]');
		assert.include(adminAccessRequestsListSource, "query: { type: 'string', nullable: true, maxLength: 128 }");
		assert.include(adminAccessRequestsListSource, "userId: { type: 'string', nullable: true, format: 'misskey:id' }");
		assert.include(adminAccessRequestsListSource, "withTotal: { type: 'boolean', default: false }");
		assert.include(adminAccessRequestsListSource, 'getManyAndCount');
		assert.include(adminAccessRequestsListSource, '"accessGrant"."reason" ILIKE :like');
		assert.include(adminAccessRequestsListSource, '"user"."username" ILIKE :like');
		assert.include(adminAppsListSource, 'enum: [...apiAppStatuses, null]');
		assert.include(adminAppsListSource, "query: { type: 'string', nullable: true, maxLength: 128 }");
		assert.include(adminAppsListSource, "userId: { type: 'string', nullable: true, format: 'misskey:id' }");
		assert.include(adminAppsListSource, "withTotal: { type: 'boolean', default: false }");
		assert.include(adminAppsListSource, 'getManyAndCount');
		assert.include(adminAppsListSource, '"app"."callbackUrls"::text ILIKE :like');
		assert.include(adminAppsListSource, '"user"."username" ILIKE :like');
		assert.include(adminTokensListSource, 'enum: [...apiTokenStatuses, null]');
		assert.include(adminTokensListSource, "query: { type: 'string', nullable: true, maxLength: 128 }");
		assert.include(adminTokensListSource, "userId: { type: 'string', nullable: true, format: 'misskey:id' }");
		assert.include(adminTokensListSource, "withTotal: { type: 'boolean', default: false }");
		assert.include(adminTokensListSource, 'getManyAndCount');
		assert.include(adminTokensListSource, '(token."isDeveloperToken" = true OR token."appId" IS NULL)');
		assert.include(adminTokensListSource, '"token"."name" ILIKE :like');
		assert.include(adminTokensListSource, '"app"."name" ILIKE :like');
		assert.include(adminTokensListSource, '"user"."username" ILIKE :like');
		assert.include(adminApiSummarySource, 'IsNull');
		assert.include(adminApiSummarySource, "{ appId: IsNull(), status: 'active' }");
		assert.include(adminApiSource, '申请人：');
		assert.include(adminApiSource, 'userAcctLabel');
		assert.include(adminApiSource, '用户 ID：');
		assert.include(adminApiSource, "os.apiWithDialog(`admin/api/apps/${action}`");
		assert.include(adminApiSource, "os.toast(`已${actionLabel(action)}应用`)");
		assert.include(adminApiSource, "admin/api/apps/${action}");
		assert.include(adminApiSource, "admin/api/access-requests/${action}");
	});

	test('backend exposes managed API endpoints and enforces API access policy', () => {
		assert.include(backendConstSource, 'read:admin:api');
		assert.include(backendConstSource, 'write:admin:api');
		assert.include(backendConstSource, "apiAccessModes = ['approval', 'open', 'closed']");
		assert.include(endpointListSource, "'api/access/status'");
		assert.include(endpointListSource, "'api/apps/create'");
		assert.include(endpointListSource, "'api/tokens/create'");
		assert.include(endpointListSource, "'admin/api/settings/update'");
		assert.include(endpointListSource, "'admin/api/access-requests/approve'");
		assert.include(endpointListSource, "'admin/api/apps/suspend'");
		assert.include(endpointListSource, "'admin/api/tokens/revoke'");
		assert.include(apiCallServiceSource, 'assertDeveloperApiAccess');
		assert.include(apiCallServiceSource, "apiMeta.apiAccessMode === 'closed'");
		assert.include(apiCallServiceSource, 'isDeveloperApiAccessApproved');
		assert.include(apiCallServiceSource, 'token.app ? token.app.userId : token.userId');
		assert.include(apiCallServiceSource, 'API_TOKEN_RATE_LIMIT_EXCEEDED');
		assert.include(apiAccessUtilsSource, 'const values = input ?? defaultApiPublicPermissions');
		assert.include(apiAccessUtilsSource, 'isDeveloperApiAccessApproved');
		assert.include(apiAccessUtilsSource, 'isSafeOAuthRedirectUri');
		assert.include(apiAccessUtilsSource, 'hasUnsafeOAuthRedirectUri');
		assert.notInclude(apiAccessUtilsSource, 'getDefaultOAuthCallbackUrl');
		assert.include(apiAccessUtilsSource, "url.protocol === 'https:' || isLoopbackHttpUrl(url)");
		assert.include(apiAccessUtilsSource, 'export function isLoopbackHttpUrl');
		assert.include(apiAccessUtilsSource, '!permission.includes(\':admin:\')');
		assert.notInclude(authenticateServiceSource, 'appCache');
		assert.notInclude(authenticateServiceSource, "createMemoryKVCache<MiApp>('app'");
		assert.include(authenticateServiceSource, 'this.appsRepository.findOneByOrFail({ id: accessToken.appId })');
		assert.include(developerTokenCreateSource, "rank: 'user'");
		assert.include(developerTokenCreateSource, 'rateLimitPerMinute: null');
		assert.include(apiDeveloperCenterMigrationSource, '{read:profile,write:notes');
		assert.include(markPersonalTokensMigrationSource, 'MarkPersonalApiTokensDeveloper1780700000003');
		assert.include(markPersonalTokensMigrationSource, 'SET "isDeveloperToken" = true');
		assert.include(markPersonalTokensMigrationSource, '"appId" IS NULL');
		assert.notInclude(apiDeveloperCenterMigrationSource, 'ADD "apiDefaultOAuthCallbackUrl"');
		assert.include(dropDefaultCallbackMigrationSource, 'DROP COLUMN IF EXISTS "apiDefaultOAuthCallbackUrl"');
		assert.notInclude(apiDeveloperCenterMigrationSource, '{read:account,write:notes');
		assert.notInclude(adminApiSettingsShowSource, 'defaultOAuthCallbackUrl');
		assert.notInclude(adminApiSettingsUpdateSource, 'defaultOAuthCallbackUrl');
		assert.notInclude(adminApiSettingsUpdateSource, 'apiDefaultOAuthCallbackUrl');
		assert.include(developerAppCreateSource, 'ps.callbackUrls !== undefined');
		assert.include(developerAppCreateSource, 'ps.callbackUrl !== undefined');
		assert.include(developerAppCreateSource, ': []');
		assert.notInclude(developerAppCreateSource, 'getDefaultOAuthCallbackUrl');
		assert.include(developerAppCreateSource, 'hasUnsafeOAuthRedirectUri(rawCallbackUrls)');
		assert.include(developerAppCreateSource, 'callbackUrl = callbackUrls[0]');
		assert.include(developerAppUpdateSource, 'callbackUrls:');
		assert.include(developerAppUpdateSource, 'hasUnsafeOAuthRedirectUri(rawCallbackUrls)');
		assert.include(developerAppUpdateSource, 'update.callbackUrls = callbackUrls');
		assert.include(adminAppUpdateSource, 'rawCallbackUrls.length === 0');
		assert.include(adminAppUpdateSource, 'update.callbackUrl = callbackUrls[0]');
		assert.notInclude(adminAppUpdateSource, 'update.callbackUrl = callbackUrls[0] ?? null');
		assert.include(oauthServiceSource, "const oidcUserinfoScopes = ['read:profile', 'read:account'] as const");
		assert.include(oauthServiceSource, "fastify.get('/userinfo'");
		assert.include(oauthServiceSource, 'token == null');
		assert.include(oauthServiceSource, "token.status && token.status !== 'active'");
		assert.include(oauthServiceSource, "token.app && token.app.status !== 'approved'");
		assert.include(oauthServiceSource, 'getApiPublicPermissions(this.instanceMeta)');
		assert.include(oauthServiceSource, 'isDeveloperApiAccessApproved');
		assert.include(oauthServiceSource, 'packOidcUserinfo(user, this.config.url)');
		assert.include(oauthServiceSource, 'unsupported_grant_type');
		assert.include(oauthServiceSource, "code_challenge_methods_supported: ['S256']");
		assert.include(oauthServiceSource, 'isValidS256PkceChallenge(codeChallenge, codeChallengeMethod)');
		assert.include(oauthServiceSource, "redirectUri.searchParams.set('code_challenge_method', 'S256')");
		assert.include(oauthServiceSource, 'verifyS256PkceCodeVerifier');
		assert.include(oauthServiceSource, 'A PKCE authorization code is required.');
		assert.include(oauthServiceSource, 'claims_supported');
		assert.notInclude(oauthServiceSource, 'this.userEntityService.pack(user, user)');
		assert.include(mastodonAppsSource, "s === 'openid' || s === 'profile'");
		assert.include(mastodonAppsSource, "pushScope.add('read:profile')");
		assert.include(mastodonAppsSource, "if (readScope.includes(s))");
		assert.include(mastodonAppsSource, 'const redirectUri = body.redirect_uris.trim()');
		assert.include(mastodonAppsSource, 'isSafeOAuthRedirectUri(redirectUri)');
		assert.include(mastodonAppsSource, 'redirect_uri: redirectUri');
		assert.notInclude(mastodonAppsSource, 'getDefaultOAuthCallbackUrl(this.instanceMeta, this.config.url)');
		assert.include(legacyAppCreateSource, "this.instanceMeta.apiAccessMode === 'closed'");
		assert.include(legacyAppCreateSource, 'ps.callbackUrls !== undefined');
		assert.include(legacyAppCreateSource, ': []');
		assert.notInclude(legacyAppCreateSource, 'getDefaultOAuthCallbackUrl');
		assert.include(authSessionGenerateSource, "this.instanceMeta.apiAccessMode === 'closed'");
		assert.include(authSessionGenerateSource, "app.status !== 'approved'");
		assert.include(authSessionGenerateSource, 'isDeveloperApiAccessApproved');
		assert.include(authAcceptSource, "this.instanceMeta.apiAccessMode === 'closed'");
		assert.include(authAcceptSource, "app.status !== 'approved'");
		assert.include(authAcceptSource, 'isDeveloperApiAccessApproved');
		assert.include(authUserkeySource, "this.instanceMeta.apiAccessMode === 'closed'");
		assert.include(authUserkeySource, "app.status !== 'approved'");
		assert.include(authUserkeySource, 'isDeveloperApiAccessApproved');
		assert.include(authUserkeySource, 'packOidcUserinfo(accessToken.user!, this.config.url)');
		assert.notInclude(authUserkeySource, 'schema: \'UserDetailedNotMe\'');
		assert.include(oauthServiceSource, 'userinfo_endpoint');
		assert.include(oauthServiceSource, "fastify.get('/jwks'");
		assert.include(wellKnownSource, "/.well-known/openid-configuration");
	});
});
